# Generated by Django 4.2 on 2023-04-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('ipaddress', models.CharField(max_length=12)),
                ('macaddress', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
